name: ci

env:
  CTEST_NO_TESTS_ACTION: error
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          mkdir -p build
          cmake -S . -B build
          make -C build
      - name: test
        run: ctest --test-dir build -V
